package com.example.usc1.core.permissions

enum class Permission(val remoteKey: String) {
    ViewDashboard("view_dashboard"),
    ViewProfile("view_profile"),
    ViewStore("view_store"),
    ViewEvents("view_events"),
    ViewPlans("view_plans"),
    ViewMembershipCard("view_membership_card"),
    ViewTraining("view_training"),
    ViewCommunity("view_community"),
    ViewOrders("view_orders"),
    ViewCollectives("view_collectives"),
    ViewLeagues("view_leagues"),
    ViewDirectory("view_directory"),
    ViewCommissions("view_commissions"),
    ViewPartners("view_partners"),
    ViewTenant("view_tenant"),
    ManageMiniVendor("manage_mini_vendor"),
    UseScanner("use_scanner"),
    ManageTenant("manage_tenant"),
    ViewGuide("view_guide"),
    ViewLegal("view_legal"),
    ViewAlbum("view_album"),
    ViewGames("view_games"),
    ViewAchievements("view_achievements"),
    ViewFidelity("view_fidelity"),
}
