package com.example.usc1.navigation

import android.net.Uri

object AppRoute {
    const val Login = "login"
    const val Register = "register"
    const val WaitingApproval = "waiting_approval"
    const val InviteRequired = "invite_required"
    const val BannedUser = "banned_user"
    const val AccountSecurity = "account_security"
    const val Dashboard = "dashboard"
    const val Profile = "profile"
    const val ProfileDetail = "profile/{userId}"
    const val Cadastro = "cadastro"
    const val Settings = "settings"
    const val SettingsInvites = "settings/invites"
    const val SettingsInvitesHistory = "settings/invites/aprovados"
    const val SettingsMentorship = "settings/mentorship"
    const val SettingsTurmaLeader = "settings/lider-turma"
    const val MembershipCard = "membership-card"
    const val Events = "events"
    const val EventDetail = "event-detail/{eventId}"
    const val EventCheckout = "event-checkout/{eventId}?lotId={lotId}"
    const val EventPartyMenu = "event-party-menu/{eventId}"
    const val EventPartyProduct = "event-party-product/{eventId}/{productId}"
    const val EventPartyVouchers = "event-party-vouchers/{eventId}"
    const val EventTickets = "event-tickets"
    const val EventTicketDetail = "event-ticket-detail/{ticketId}"
    const val EventOrders = "event-orders"
    const val EventOrderDetail = "event-order-detail/{orderId}"
    const val Store = "store"
    const val ProductDetail = "store-product/{productId}"
    const val Cart = "cart"
    const val Checkout = "checkout"
    const val StoreOrders = "store-orders"
    const val StoreOrderDetail = "store-order/{orderId}"
    const val Plans = "plans"
    const val PlanDetail = "plan-detail/{planId}"
    const val UserPlanStatus = "plan-status"
    const val PlanOrders = "plan-orders"
    const val Training = "training"
    const val TrainingDetail = "training/{trainingId}"
    const val Gym = "gym"
    const val Ranking = "ranking"
    const val RankingTurma = "ranking/{turmaId}"
    const val History = "historico"
    const val HistoryOrganogram = "historico/organograma"
    const val Company = "empresa"
    const val CompanyRegister = "empresa/cadastro"
    const val CompanyDashboard = "empresa/{companyId}"
    const val CompanyEdit = "empresa/{companyId}/editar"
    const val CompanyHistory = "empresa/{companyId}/historico"
    const val Partners = "partners"
    const val PartnerDetail = "partner-detail/{partnerId}"
    const val PartnerBenefits = "partner-benefits/{partnerId}"
    const val Community = "community"
    const val CommunityPostDetail = "community-post/{postId}"
    // Coletivos: área pública espelhando /ligas_usc, /comissoes e /diretorio do web.
    const val Leagues = "leagues"
    const val LeagueDetail = "league-detail/{leagueId}"
    const val LeagueMembers = "league-members/{leagueId}"
    const val LeagueAgenda = "league-agenda/{leagueId}"
    const val LeagueStore = "league-store/{leagueId}"
    /** Raiz `/diretorio`: usa o registro primário do diretório. */
    const val Directory = "directory"
    const val DirectoryRootMembers = "directory-root-members"
    const val DirectoryRootAgenda = "directory-root-agenda"
    const val DirectoryRootStore = "directory-root-store"
    const val DirectoryDetail = "directory-detail/{directoryId}"
    const val DirectoryMembers = "directory-members/{directoryId}"
    const val DirectoryAgenda = "directory-agenda/{directoryId}"
    const val DirectoryStore = "directory-store/{directoryId}"
    const val Commissions = "commissions"
    const val CommissionDetail = "commission-detail/{commissionId}"
    const val CommissionMembers = "commission-members/{commissionId}"
    const val CommissionAgenda = "commission-agenda/{commissionId}"
    const val CommissionStore = "commission-store/{commissionId}"
    const val Tenant = "tenant"
    const val MiniVendor = "mini-vendor"
    const val MiniVendorEdit = "mini-vendor-edit"
    const val MiniVendorManagement = "mini-vendor-management"
    const val MiniVendorProducts = "mini-vendor-products"
    const val MiniVendorPendingOrders = "mini-vendor-pending-orders"
    const val MiniVendorApprovedOrders = "mini-vendor-approved-orders"
    const val MiniVendorPendingOrdersByCategory = "mini-vendor-pending-orders/{category}"
    const val MiniVendorApprovedOrdersByCategory = "mini-vendor-approved-orders/{category}"
    const val MiniVendorFinance = "mini-vendor-finance"
    const val SalesMode = "sales-mode"
    const val SalesModeEventMenu = "sales-mode-event-menu"
    const val Scanner = "scanner"
    const val EventCheckInScanner = "scanner-events"
    const val PartyScanner = "scanner-parties"
    const val ProductWithdrawalScanner = "scanner-products"
    const val ScannerSuccess = "scanner-success"
    const val ScannerError = "scanner-error"
    const val ScannerPermissionDenied = "scanner-permission-denied"
    const val Guide = "guide"
    const val Legal = "legal"
    const val Faq = "faq"
    const val ContactUsc = "contact-usc"
    const val Support = "support"
    const val Terms = "terms"
    const val PrivacyLgpd = "privacy-lgpd"
    const val LgpdRequest = "lgpd-request"
    const val LegalDocument = "legal-document"
    const val LegalDocumentBySlug = "legal-document/{slug}"
    const val Album = "album"
    const val AlbumTurma = "album-turma/{turmaId}"
    const val CacaCalouro = "caca-calouro"
    const val CalouroRanking = "calouro-ranking"
    const val Games = "games"
    const val Boardround = "boardround"
    const val BoardroundRanking = "boardround-ranking"
    const val BoardroundStats = "boardround-stats"
    const val Achievements = "achievements"
    const val Loyalty = "fidelity"
    const val GameRules = "game-rules"
    const val OrdersHub = "orders"
    const val OrdersByType = "orders-by-type/{type}?status={status}"
    const val UserOrderDetail = "user-order/{tab}/{status}/{orderId}"
    const val UserOrderTicketDetail = "user-order/{tab}/{status}/{orderId}/ingressos/{ticketToken}"
    const val Admin = "admin"
    const val AdminDashboardModules = "admin/dashboard-modulos"
    const val AdminPolicies = "admin/politicas"
    const val AdminUsers = "admin/usuarios"
    const val AdminUserDetail = "admin/usuarios/{userId}"
    const val AdminPermissionUsers = "admin/permissoes/usuarios"
    const val AdminReports = "admin/denuncias"
    const val AdminReportsBanned = "admin/denuncias/banidos"
    const val AdminReportsCommunity = "admin/denuncias/comunidade"
    const val AdminReportsGym = "admin/denuncias/gym"
    const val AdminReportsSupport = "admin/denuncias/suporte"
    const val AdminStore = "admin/loja"
    const val AdminStoreCategories = "admin/loja/categorias"
    const val AdminStoreProducts = "admin/loja/produtos"
    const val AdminStoreNewProduct = "admin/loja/produtos/novo"
    const val AdminStoreDisabledProducts = "admin/loja/produtos-desativados"
    const val AdminStoreReviews = "admin/loja/review"
    const val AdminStorePendingOrders = "admin/loja/pedidos-pendentes"
    const val AdminStoreApprovedOrders = "admin/loja/pedidos-aprovados"
    const val AdminStorePendingOrdersByCategory = "admin/loja/pedidos-pendentes/{category}"
    const val AdminStoreApprovedOrdersByCategory = "admin/loja/pedidos-aprovados/{category}"
    const val AdminPartners = "admin/parceiros"
    const val AdminPartnersActive = "admin/parceiros/ativos"
    const val AdminPartnersCompanies = "admin/parceiros/empresas"
    const val AdminPartnersData = "admin/parceiros/dados"
    const val AdminPartnersHistory = "admin/parceiros/historico"
    const val AdminPlans = "admin/planos"
    const val AdminPlansHistory = "admin/planos/historico"
    const val AdminPlansAudit = "admin/planos/auditoria"
    const val AdminPlansEdit = "admin/planos/editar"
    const val AdminPlansBichoSolto = "admin/planos/lista_bicho_solto"
    const val AdminPlansCardumeLivre = "admin/planos/lista_cardume_livre"
    const val AdminPlansAtleta = "admin/planos/lista_atleta"
    const val AdminPlansLenda = "admin/planos/lista_lenda"
    const val AdminManagement = "admin/gestao"
    const val AdminManagementEvents = "admin/gestao/eventos"
    const val AdminManagementStore = "admin/gestao/loja"
    const val AdminManagementTraining = "admin/gestao/treinos"
    const val AdminManagementFinance = "admin/gestao/financeiro"
    const val AdminBiCommercial = "admin/bi/comercial"
    const val AdminBiOperational = "admin/bi/operacional"
    const val AdminBiGate = "admin/bi/portaria"
    const val AdminAlbum = "admin/album"
    const val AdminAlbumCacaCalouro = "admin/album/caca_calouro"
    const val AdminAlbumPontuaCalouro = "admin/album/pontua_calouro"
    const val AdminAlbumPontuaGeral = "admin/album/pontua_geral"
    const val AdminAlbumCustomization = "admin/album/customizacao"
    const val AdminClass = "admin/turma"
    const val AdminGames = "admin/games"
    const val AdminDatabaseScanner = "admin/scanner"
    const val AdminMentorship = "admin/apadrinhamento"
    const val AdminLogs = "admin/logs"
    const val AdminMiniVendors = "admin/mini-vendors"
    const val AdminMiniVendorApprovals = "admin/mini-vendors/aprovacoes"
    const val AdminMiniVendorVendors = "admin/mini-vendors/cadastros"

    fun profileDetail(userId: String) = "profile/${Uri.encode(userId)}"
    fun eventDetail(eventId: String) = "event-detail/$eventId"
    fun eventCheckout(eventId: String, lotId: String = "") =
        "event-checkout/${Uri.encode(eventId)}?lotId=${Uri.encode(lotId)}"
    fun eventPartyMenu(eventId: String) = "event-party-menu/${Uri.encode(eventId)}"
    fun eventPartyProduct(eventId: String, productId: String) =
        "event-party-product/${Uri.encode(eventId)}/${Uri.encode(productId)}"
    fun eventPartyVouchers(eventId: String) = "event-party-vouchers/${Uri.encode(eventId)}"
    fun eventTicketDetail(ticketId: String) = "event-ticket-detail/${Uri.encode(ticketId)}"
    fun eventOrderDetail(orderId: String) = "event-order-detail/$orderId"
    fun productDetail(productId: String) = "store-product/$productId"
    fun storeOrderDetail(orderId: String) = "store-order/$orderId"
    fun planDetail(planId: String) = "plan-detail/$planId"
    fun trainingDetail(trainingId: String) = "training/${Uri.encode(trainingId)}"
    fun legalDocumentBySlug(slug: String) = "legal-document/${Uri.encode(slug)}"
    fun rankingTurma(turmaId: String) = "ranking/${Uri.encode(turmaId)}"
    fun companyDashboard(companyId: String) = "empresa/${Uri.encode(companyId)}"
    fun companyEdit(companyId: String) = "empresa/${Uri.encode(companyId)}/editar"
    fun companyHistory(companyId: String) = "empresa/${Uri.encode(companyId)}/historico"
    fun partnerDetail(partnerId: String) = "partner-detail/$partnerId"
    fun partnerBenefits(partnerId: String) = "partner-benefits/$partnerId"
    fun communityPostDetail(postId: String) = "community-post/$postId"
    fun leagueDetail(leagueId: String) = "league-detail/$leagueId"
    fun leagueMembers(leagueId: String) = "league-members/$leagueId"
    fun leagueAgenda(leagueId: String) = "league-agenda/$leagueId"
    fun leagueStore(leagueId: String) = "league-store/$leagueId"
    fun directoryDetail(directoryId: String) = "directory-detail/$directoryId"
    fun directoryMembers(directoryId: String) = "directory-members/$directoryId"
    fun directoryAgenda(directoryId: String) = "directory-agenda/$directoryId"
    fun directoryStore(directoryId: String) = "directory-store/$directoryId"
    fun commissionDetail(commissionId: String) = "commission-detail/$commissionId"
    fun commissionMembers(commissionId: String) = "commission-members/$commissionId"
    fun commissionAgenda(commissionId: String) = "commission-agenda/$commissionId"
    fun commissionStore(commissionId: String) = "commission-store/$commissionId"
    fun albumTurma(turmaId: String) = "album-turma/$turmaId"
    fun ordersByType(type: String, status: String = "pendentes") =
        "orders-by-type/${Uri.encode(type)}?status=${Uri.encode(status)}"

    fun userOrderDetail(tab: String, status: String, orderId: String) =
        "user-order/${Uri.encode(tab)}/${Uri.encode(status)}/${Uri.encode(orderId)}"

    fun userOrderTicketDetail(tab: String, status: String, orderId: String, ticketToken: String) =
        "user-order/${Uri.encode(tab)}/${Uri.encode(status)}/${Uri.encode(orderId)}" +
            "/ingressos/${Uri.encode(ticketToken)}"

    fun miniVendorPendingOrdersByCategory(category: String) =
        "mini-vendor-pending-orders/${Uri.encode(category)}"

    fun miniVendorApprovedOrdersByCategory(category: String) =
        "mini-vendor-approved-orders/${Uri.encode(category)}"
    fun adminUserDetail(userId: String) = "admin/usuarios/$userId"
    fun adminStorePendingOrdersByCategory(category: String) = "admin/loja/pedidos-pendentes/${Uri.encode(category)}"
    fun adminStoreApprovedOrdersByCategory(category: String) = "admin/loja/pedidos-aprovados/${Uri.encode(category)}"
}
