package com.example.usc1.navigation

object AppRoute {
    const val Login = "login"
    const val Register = "register"
    const val WaitingApproval = "waiting_approval"
    const val InviteRequired = "invite_required"
    const val BannedUser = "banned_user"
    const val AccountSecurity = "account_security"
    const val Dashboard = "dashboard"
    const val Profile = "profile"
    const val Settings = "settings"
    const val MembershipCard = "membership-card"
    const val Events = "events"
    const val EventDetail = "event-detail/{eventId}"
    const val EventCheckout = "event-checkout/{eventId}"
    const val EventTickets = "event-tickets"
    const val EventTicketDetail = "event-ticket-detail/{ticketId}"
    const val EventOrders = "event-orders"
    const val EventOrderDetail = "event-order-detail/{orderId}"
    const val Store = "store"
    const val ProductDetail = "store-product/{productId}"
    const val Cart = "cart"
    const val Checkout = "checkout"
    const val StoreOrders = "store-orders"
    const val StoreOrderDetail = "store-order/{orderId}"
    const val Plans = "plans"
    const val PlanDetail = "plan-detail/{planId}"
    const val UserPlanStatus = "plan-status"
    const val PlanOrders = "plan-orders"
    const val Training = "training"
    const val Gym = "gym"
    const val TrainingCheckIn = "training-checkin"
    const val TrainingCheckInDetail = "training-checkin-detail/{checkInId}"
    const val TrainingFrequency = "training-frequency"
    const val TrainingHistory = "training-history"
    const val Partners = "partners"
    const val PartnerDetail = "partner-detail/{partnerId}"
    const val PartnerBenefits = "partner-benefits/{partnerId}"

    fun eventDetail(eventId: String) = "event-detail/$eventId"
    fun eventCheckout(eventId: String) = "event-checkout/$eventId"
    fun eventTicketDetail(ticketId: String) = "event-ticket-detail/$ticketId"
    fun eventOrderDetail(orderId: String) = "event-order-detail/$orderId"
    fun productDetail(productId: String) = "store-product/$productId"
    fun storeOrderDetail(orderId: String) = "store-order/$orderId"
    fun planDetail(planId: String) = "plan-detail/$planId"
    fun trainingCheckInDetail(checkInId: String) = "training-checkin-detail/$checkInId"
    fun partnerDetail(partnerId: String) = "partner-detail/$partnerId"
    fun partnerBenefits(partnerId: String) = "partner-benefits/$partnerId"
}
