// src/constants/userDefaults.ts

// 1. Estatísticas Padrão (DNA do Tubarão)
export const DEFAULT_STATS = {
    accountCreated: 1,
    inviteActivations: 0,
    mentorsCount: 0,
    menteesCount: 0,
    loginCount: 1,
    profileComplete: 0,
    postsCount: 0,
    commentsCount: 0,
    likesReceived: 0,
    likesGiven: 0,
    hypesGiven: 0,
    validReports: 0,
    followersCount: 0,
    followingCount: 0,
    loginStreak: 0,
    gymCheckins: 0,
    gymEarlyBird: 0,
    gymNightOwl: 0,
    gymStreak: 0,
    treinoRsvps: 0,
    treinoPresenceConfirmed: 0,
    trainingLikesGiven: 0,
    confirmedTrainings: 0,
    arenaMatches: 0,
    arenaWins: 0,
    arenaLosses: 0,
    arenaLossStreak: 0,
    arenaLoseStreak: 0,
    storeSpent: 0,
    moneySpent: 0,
    storeOrders: 0,
    albumCollected: 0,
    storeItemsCount: 0,
    uniqueProductsBought: 0,
    reviewsGiven: 0,
    miniVendorCreated: 0,
    miniVendorOrders: 0,
    planUpdates: 0,
    semesterPlanActive: 0,
    leagueMemberships: 0,
    leaguesCreated: 0,
    eventsCreated: 0,
    leagueQuizRuns: 0,
    leagueLikesGiven: 0,
    pollAnswers: 0,
    eventEntries: 0,
    eventsAttended: 0,
    eventsBought: 0,
    promoTicketsBought: 0,
    academicEvents: 0,
    socialActions: 0,
    totalSpentEvents: 0,
    eventsPromo: 0,
    eventsAcademic: 0,
    solidarityCount: 0,
    freshersHuntScans: 0,
    gotScanned: 0,
    scansT8: 0
};

// 2. Propriedades Padrão do Usuário (Pele do Tubarão)
export const DEFAULT_USER_PROPS = {
    // Gamificação Inicial
    xp: 50,
    xpMultiplier: 1.0,
    level: 1,
    patente: "Plâncton",
    tier: "bicho",
    sharkCoins: 0,
    selos: 0,

    // Plano Inicial (Free)
    plano: "Bicho Solto",
    plano_status: "ativo",
    plano_badge: "Bicho Solto",
    plano_cor: "zinc",
    plano_icon: "ghost",
    desconto_loja: 0,
    nivel_prioridade: 1,

    // Configurações do Sistema
    role: "guest",
    status: "ativo",
    isAnonymous: false,
    idadePublica: true,
    relacionamentoPublico: false,
    whatsappPublico: false,
    instagramPublico: false,
    signoPublico: false,
    ascendentePublico: false,
};
