export const PUBLIC_PATHS = [
  "/login",
  "/",
  "/visitante",
  "/convite-necessario",
  "/nova-atletica",
  "/faq",
  "/contato-usc",
  "/politica-privacidade",
  "/termos-de-servico",
  "/politica-cookies",
  "/direitos-lgpd",
  "/direitos-lgpd/solicitar",
  "/termo-confidencialidade-admin",
  "/termos-tenants-organizadores",
  "/legal",
  "/historico",
  "/cadastro",
  "/configuracoes/termos",
  "/empresa/cadastro",
  "/recuperar-senha",
  "/sem-permissao",
  "/banned",
  "/em-breve",
  "/nao-encontrado",
];

export const GUEST_ALLOWED_PATHS = [...PUBLIC_PATHS, "/dashboard"];

export const COMING_SOON_PATHS = ["/carrinho", "/checkout"];

export type AppPageDefinition = {
  path: string;
  label: string;
  permissionPath?: string;
};

const PATH_LABEL_OVERRIDES: Record<string, string> = {
  "/admin": "Admin Dashboard",
  "/admin/atletica": "Atlética",
  "/admin/bi": "BI Eventos",
  "/admin/bi/comercial": "BI Comercial",
  "/admin/bi/operacional": "BI Operacional",
  "/admin/bi/portaria": "BI Portaria",
  "/admin/bi/estrategico": "BI Estratégico",
  "/admin/bi/vendas": "BI Modo Vendas",
  "/admin/gestao": "Gestão",
  "/admin/dashboard-modulos": "Dashboard Módulos",
  "/admin/eventos/encerrados": "Admin Eventos Encerrados",
  "/admin/eventos/[id]": "Admin Evento Painel",
  "/admin/eventos/[id]/bi": "Admin Evento BI",
  "/admin/eventos/[id]/checkins": "Admin Evento Lista de Presença",
  "/admin/eventos/[id]/cupons": "Admin Evento Cupons",
  "/admin/eventos/[id]/edicao": "Admin Evento Edição",
  "/admin/eventos/[id]/enquetes": "Admin Evento Enquetes",
  "/admin/eventos/[id]/extrato": "Admin Evento Extrato",
  "/admin/eventos/[id]/ficha": "Admin Evento Modo Vendas",
  "/admin/eventos/[id]/ficha/pagamento": "Admin Evento Pagamentos",
  "/admin/eventos/[id]/ficha/produto": "Admin Evento Produto",
  "/admin/eventos/[id]/ficha/produtos": "Admin Evento Produtos",
  "/admin/eventos/[id]/ficha/produtos/cadastro": "Admin Evento Cadastro Produto",
  "/admin/eventos/[id]/ficha/retirada": "Admin Evento Retirada",
  "/admin/eventos/[id]/ingressos": "Admin Evento Ingressos",
  "/admin/eventos/[id]/lotes": "Admin Evento Lotes",
  "/admin/eventos/[id]/recebedores": "Admin Evento Recebedores",
  "/admin/eventos/[id]/scan": "Admin Evento Scan",
  "/admin/eventos/lista/[id]": "Admin Evento Detalhe",
  "/admin/gestao/eventos": "BI Eventos",
  "/admin/gestao/financeiro": "Financeiro",
  "/admin/gestao/loja": "BI Loja",
  "/admin/gestao/produtos": "BI Loja",
  "/admin/gestao/treinos": "BI Treinos",
  "/admin/ligas": "Admin Ligas",
  "/admin/comissoes": "Admin Comissões",
  "/admin/diretorio": "Admin Diretório",
  "/admin/master": "Admin Master",
  "/admin/boardround": "Admin BoardRound",
  "/admin/apadrinhamento": "Admin Apadrinhamento",
  "/admin/loja/pedidos-aprovados": "Loja Pedidos Aprovados",
  "/admin/permissoes": "Permissões",
  "/admin/permissoes/usuarios": "Permissões Usuários",
  "/admin/scanner": "Scanner QR",
  "/admin/scan-festas": "Scan Eventos",
  "/admin/scan-eventos": "Scan Eventos",
  "/admin/eventos/scan/[id]": "Scan Evento",
  "/scanner": "Scanner",
  "/admin/treinos/lista/[id]": "Admin Treino Lista",
  "/admin/usuarios/[id]": "Admin Usuário Detalhe",
  "/admin/usuarios/cadastro": "Admin Cadastro Config",
  "/boardround": "BoardRound",
  "/boardround/estatisticas": "BoardRound Estatísticas",
  "/boardround/ranking": "BoardRound Ranking",
  "/album/[turmaId]": "Album da Turma",
  "/empresa/[id]": "Empresa Parceira",
  "/empresa/[id]/historico": "Empresa Histórico",
  "/eventos/[id]": "Evento Detalhe",
  "/eventos/[id]/produtos": "Produtos do Evento",
  "/eventos/[id]/produtos/[productId]": "Produto do Evento",
  "/eventos/[id]/produtos/fichas": "Minhas Fichas do Evento",
  "/historico/organograma": "Organograma",
  "/ligas_usc": "Ligas USC",
  "/ligas_usc/[leagueId]": "Liga USC",
  "/ligas_usc/[leagueId]/membros": "Liga USC - Membros",
  "/ligas_usc/[leagueId]/agenda": "Liga USC - Agenda",
  "/ligas_usc/[leagueId]/loja": "Liga USC - Loja",
  "/comissoes": "Comissões",
  "/comissoes/[leagueId]": "Comissão",
  "/comissoes/[leagueId]/membros": "Comissão - Membros",
  "/comissoes/[leagueId]/agenda": "Comissão - Agenda",
  "/comissoes/[leagueId]/loja": "Comissão - Loja",
  "/comissoes/configurar/[leagueId]/gestao/financeiro": "Comissão - Financeiro",
  "/diretorio": "Diretório",
  "/diretorio/[leagueId]": "Diretório",
  "/diretorio/[leagueId]/membros": "Diretório - Membros",
  "/diretorio/[leagueId]/agenda": "Diretório - Agenda",
  "/diretorio/[leagueId]/loja": "Diretório - Loja",
  "/diretorio/configurar/[leagueId]/gestao/financeiro": "Diretório - Financeiro",
  "/ligas/[leagueId]/gestao": "Liga - Gestão Financeira",
  "/ligas/[leagueId]/gestao/financeiro": "Liga - Financeiro",
  "/loja/[id]": "Produto Loja",
  "/loja/[id]/review": "Review do Produto",
  "/master": "Dashboard Master",
  "/faq": "FAQ USC",
  "/master/contato": "Contato USC",
  "/master/contato/respondidas": "Contato USC - Respondidas",
  "/master/faq": "FAQ USC",
  "/master/privacy": "Privacidade e Termos",
  "/master/privacy/[slug]": "Edição de Documento Legal",
  "/politica-privacidade": "Política de Privacidade",
  "/termos-de-servico": "Termos de Serviço",
  "/politica-cookies": "Política de Cookies",
  "/direitos-lgpd": "Direitos LGPD",
  "/direitos-lgpd/solicitar": "Solicitação LGPD",
  "/termo-confidencialidade-admin": "Sigilo Administrativo",
  "/termos-tenants-organizadores": "Termos para Tenants",
  "/legal/[slug]": "Documento Legal",
  "/master/landing": "Landing USC",
  "/master/permissoes": "Permissões Globais",
  "/master/permissoes/perfis-admin": "Perfis do Admin",
  "/master/solicitacoes": "Solicitações da Plataforma",
  "/master/tenants/[tenantId]": "Tenant Detalhe",
  "/master/tenants": "Tenants",
  "/nova-atletica": "Onboarding Atlética",
  "/parceiros/[id]": "Parceiro Detalhe",
  "/configuracoes/convites": "Meus Convites",
  "/configuracoes/convites/aprovados": "Convites Aprovados",
  "/configuracoes/mini-vendor/gestao/financeiro": "Mini Vendor - Financeiro",
  "/perfil/[id]": "Perfil Público",
  "/configuracoes/apadrinhamento": "Apadrinhamento",
  "/perfil/mini-vendor": "Perfil Público Mini Vendor",
  "/perfil/mini-vendor/[id]": "Perfil Público Mini Vendor",
  "/ranking/[turmaId]": "Ranking da Turma",
  "/treinos/[id]": "Treino Detalhe",
};

const ADMIN_PAGE_PATHS = [
  "/admin",
  "/admin/album",
  "/admin/apadrinhamento",
  "/admin/album/caca_calouro",
  "/admin/album/customizacao",
  "/admin/album/pontua_calouro",
  "/admin/album/pontua_geral",
  "/admin/atletica",
  "/admin/bi",
  "/admin/bi/comercial",
  "/admin/bi/operacional",
  "/admin/bi/portaria",
  "/admin/bi/estrategico",
  "/admin/bi/vendas",
  "/admin/carteirinha",
  "/admin/comissoes",
  "/admin/comunidade",
  "/admin/configuracoes",
  "/admin/conquistas",
  "/admin/dashboard-modulos",
  "/admin/denuncias",
  "/admin/denuncias/banidos",
  "/admin/denuncias/comunidade",
  "/admin/denuncias/gym",
  "/admin/denuncias/suporte",
  "/admin/diretorio",
  "/admin/eventos",
  "/admin/eventos/[id]",
  "/admin/eventos/[id]/bi",
  "/admin/eventos/[id]/checkins",
  "/admin/eventos/[id]/cupons",
  "/admin/eventos/[id]/edicao",
  "/admin/eventos/[id]/enquetes",
  "/admin/eventos/[id]/extrato",
  "/admin/eventos/[id]/ficha",
  "/admin/eventos/[id]/ficha/pagamento",
  "/admin/eventos/[id]/ficha/produto",
  "/admin/eventos/[id]/ficha/produtos",
  "/admin/eventos/[id]/ficha/produtos/cadastro",
  "/admin/eventos/[id]/ficha/retirada",
  "/admin/eventos/[id]/ingressos",
  "/admin/eventos/[id]/lotes",
  "/admin/eventos/[id]/recebedores",
  "/admin/eventos/[id]/scan",
  "/admin/eventos/encerrados",
  "/admin/eventos/lista/[id]",
  "/admin/fidelidade",
  "/admin/games",
  "/admin/gestao",
  "/admin/gestao/financeiro",
  "/admin/gestao/eventos",
  "/admin/gestao/loja",
  "/admin/gestao/produtos",
  "/admin/gestao/treinos",
  "/admin/guia",
  "/admin/gym",
  "/admin/historico",
  "/admin/historico/organograma",
  "/admin/lancamento",
  "/admin/lancamento/ativacoes",
  "/admin/lancamento/convites",
  "/admin/lancamento/pendentes",
  "/admin/landing",
  "/admin/ligas",
  "/admin/logs",
  "/admin/loja",
  "/admin/loja/categorias",
  "/admin/loja/pedidos-aprovados",
  "/admin/loja/pedidos-pendentes",
  "/admin/loja/produtos-desativados",
  "/admin/loja/produtos",
  "/admin/loja/review",
  "/admin/master",
  "/admin/master/lancamento",
  "/admin/master/lancamento/ativacoes",
  "/admin/master/lancamento/convites",
  "/admin/master/lancamento/pendentes",
  "/admin/mini-vendors",
  "/admin/mini-vendors/aprovacoes",
  "/admin/mini-vendors/cadastros",
  "/admin/parceiros",
  "/admin/parceiros/ativos",
  "/admin/parceiros/dados",
  "/admin/parceiros/empresas",
  "/admin/parceiros/historico",
  "/admin/permissoes",
  "/admin/permissoes/usuarios",
  "/admin/planos",
  "/admin/planos/auditoria",
  "/admin/planos/editar",
  "/admin/planos/historico",
  "/admin/planos/lista_atleta",
  "/admin/planos/lista_bicho_solto",
  "/admin/planos/lista_cardume_livre",
  "/admin/planos/lista_lenda",
  "/admin/scanner",
  "/admin/scan-festas",
  "/admin/scan-eventos",
  "/admin/eventos/scan/[id]",
  "/admin/boardround",
  "/admin/treinos",
  "/admin/treinos/antigos",
  "/admin/treinos/lista/[id]",
  "/admin/turma",
  "/admin/usuarios",
  "/admin/usuarios/cadastro",
  "/admin/usuarios/[id]",
] as const;

const MASTER_PAGE_PATHS = [
  "/master",
  "/master/contato",
  "/master/contato/respondidas",
  "/master/faq",
  "/master/landing",
  "/master/lancamento",
  "/master/lancamento/ativacoes",
  "/master/lancamento/convites",
  "/master/lancamento/pendentes",
  "/master/permissoes",
  "/master/permissoes/perfis-admin",
  "/master/privacy",
  "/master/privacy/[slug]",
  "/master/solicitacoes",
  "/master/tenants",
  "/master/tenants/[tenantId]",
] as const;

const MEMBER_PAGE_PATHS = [
  "/aguardando-aprovacao",
  "/banned",
  "/album",
  "/album/[turmaId]",
  "/cadastro",
  "/carrinho",
  "/carteirinha",
  "/checkout",
  "/comissoes",
  "/comissoes/[leagueId]",
  "/comissoes/[leagueId]/membros",
  "/comissoes/[leagueId]/agenda",
  "/comissoes/[leagueId]/loja",
  "/comissoes/configurar/[leagueId]/gestao/financeiro",
  "/comunidade",
  "/configuracoes",
  "/configuracoes/apadrinhamento",
  "/configuracoes/convites",
  "/configuracoes/convites/aprovados",
  "/configuracoes/lider-turma",
  "/configuracoes/mini-vendor",
  "/configuracoes/mini-vendor/editar",
  "/configuracoes/mini-vendor/gestao/financeiro",
  "/configuracoes/mini-vendor/pedidos-aprovados",
  "/configuracoes/mini-vendor/pedidos-pendentes",
  "/configuracoes/mini-vendor/produtos",
  "/configuracoes/pedidos",
  "/configuracoes/pedidos/eventos",
  "/configuracoes/pedidos/loja",
  "/configuracoes/pedidos/planos",
  "/configuracoes/seguranca",
  "/configuracoes/suporte",
  "/configuracoes/termos",
  "/conquistas",
  "/contato-usc",
  "/dashboard",
  "/diretorio",
  "/diretorio/[leagueId]",
  "/diretorio/[leagueId]/membros",
  "/diretorio/[leagueId]/agenda",
  "/diretorio/[leagueId]/loja",
  "/diretorio/configurar/[leagueId]/gestao/financeiro",
  "/em-breve",
  "/empresa",
  "/empresa/[id]",
  "/empresa/[id]/historico",
  "/empresa/cadastro",
  "/eventos",
  "/eventos/[id]",
  "/eventos/[id]/produtos",
  "/eventos/[id]/produtos/[productId]",
  "/eventos/[id]/produtos/fichas",
  "/eventos/compra",
  "/faq",
  "/fidelidade",
  "/games",
  "/guia",
  "/gym",
  "/gym/checkin",
  "/gym/checkin/details",
  "/historico",
  "/historico/organograma",
  "/ligas",
  "/ligas/[leagueId]/gestao",
  "/ligas/[leagueId]/gestao/financeiro",
  "/ligas_usc",
  "/ligas_usc/[leagueId]",
  "/ligas_usc/[leagueId]/membros",
  "/ligas_usc/[leagueId]/agenda",
  "/ligas_usc/[leagueId]/loja",
  "/login",
  "/loja",
  "/loja/[id]",
  "/loja/[id]/review",
  "/nao-encontrado",
  "/nova-atletica",
  "/parceiros",
  "/parceiros/[id]",
  "/politica-privacidade",
  "/termos-de-servico",
  "/politica-cookies",
  "/direitos-lgpd",
  "/direitos-lgpd/solicitar",
  "/termo-confidencialidade-admin",
  "/termos-tenants-organizadores",
  "/legal/[slug]",
  "/perfil",
  "/perfil/[id]",
  "/perfil/mini-vendor",
  "/perfil/mini-vendor/[id]",
  "/planos",
  "/planos/adesao",
  "/ranking",
  "/ranking/[turmaId]",
  "/sem-permissao",
  "/boardround",
  "/boardround/estatisticas",
  "/boardround/ranking",
  "/treinos",
  "/treinos/[id]",
  "/scanner",
  "/visitante",
  "/convite-necessario",
] as const;

const titleizeSegment = (segment: string): string =>
  segment
    .replace(/^\[(.+)\]$/, "$1")
    .replace(/-/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

export const resolveAppPageLabel = (path: string): string => {
  const cleanPath = path.trim();
  if (PATH_LABEL_OVERRIDES[cleanPath]) {
    return PATH_LABEL_OVERRIDES[cleanPath];
  }

  const segments = cleanPath.split("/").filter(Boolean);
  if (!segments.length) return "Home";

  return segments.map((segment) => titleizeSegment(segment)).join(" / ");
};

const page = (
  path: string,
  options?: Pick<Partial<AppPageDefinition>, "label" | "permissionPath">
): AppPageDefinition => ({
  path,
  label: options?.label || resolveAppPageLabel(path),
  ...(options?.permissionPath ? { permissionPath: options.permissionPath } : {}),
});

export const APP_PAGES: AppPageDefinition[] = [
  ...ADMIN_PAGE_PATHS.map((path) =>
    path === "/admin/atletica"
      ? page(path, { permissionPath: "/admin/configuracoes" })
      : path === "/admin/boardround"
      ? page(path, { permissionPath: "/admin/sharkround" })
      : path.startsWith("/admin/bi/")
        ? page(path, { permissionPath: "/admin/bi" })
      : path === "/admin/gestao" || path === "/admin/gestao/eventos"
        ? page(path, { permissionPath: "/admin/bi" })
      : path === "/admin/gestao/financeiro"
        ? page(path, { permissionPath: "/admin/gestao" })
        : path === "/admin/historico/organograma"
          ? page(path, { permissionPath: "/admin/historico" })
      : path === "/admin/loja/pedidos-aprovados"
        ? page(path, { permissionPath: "/admin/loja" })
      : path === "/admin/usuarios/cadastro"
        ? page(path, { permissionPath: "/admin/usuarios" })
      : page(path)
  ),
  ...MASTER_PAGE_PATHS.map((path) => page(path)),
  ...MEMBER_PAGE_PATHS.map((path) =>
    path === "/boardround"
      ? page(path, { permissionPath: "/sharkround" })
      : path === "/boardround/estatisticas"
        ? page(path, { permissionPath: "/sharkround/estatisticas" })
        : path === "/boardround/ranking"
          ? page(path, { permissionPath: "/sharkround/ranking" })
          : path === "/ligas_usc"
            ? page(path, { permissionPath: "/ligas_unitau" })
            : path === "/historico/organograma"
              ? page(path, { permissionPath: "/historico" })
              : page(path)
  ),
].sort((left, right) => left.path.localeCompare(right.path, "pt-BR"));
